server:
  port: 8080

spring:
  application:
    name: reciclaje-backend

  jackson:
    time-zone: America/Santiago

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/reciclaje_db}
    username: ${SPRING_DATASOURCE_USERNAME:reciclaje_user}
    password: ${SPRING_DATASOURCE_PASSWORD:reciclaje_pass_2026}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:init-data.sql

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: ${SPRING_JPA_FORMAT_SQL:false}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    org.hibernate.SQL: ${LOGGING_LEVEL_HIBERNATE_SQL:OFF}
    org.hibernate.type.descriptor.sql.BasicBinder: ${LOGGING_LEVEL_HIBERNATE_BINDER:OFF}
    org.hibernate: ${LOGGING_LEVEL_HIBERNATE:WARN}

# Configuración de Seguridad & JWT
jwt:
  secret: ${JWT_SECRET:ReciclajeLitoralSuperSecretKey2026WithEnoughBitLengthForHMACSHA256Signature!}
  expiration-ms: 604800000 # 7 días (1 semana)

# Configuración de AWS S3 desde variables de entorno y perfil AWS
aws:
  profile: ${AWS_PROFILE:}
  access-key-id: ${AWS_ACCESS_KEY_ID:}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY:}
  s3:
    bucket-name: ${AWS_S3_BUCKET:reciclaje-litoral-fotos-prod}
    region: ${AWS_REGION:us-east-1}
